### ISSUE TITLE
Dev Repo

### ISSUE THREAD

**Issue by florian-asche** [jnsbyr/fhem#1]
Hi,

ist das hier ein DEV oder ein Prod Repo?

Hast du interesse deine Module im Zentralen FHEM Projekt getrennt zu verwalten? Siehe hier: https://github.com/fhem

Wir helfen gerne bei dem Umzug und zeigen dir auch wie du ein Fhem Update fähiges Repo erstellen kannst.

**Comment by jnsbyr** [comment]
Hi Florian,

danke der Nachfrage. Das hier ist mein Development-Repo für die FHEM-Module, für die ich selbst Maintainer bin, sowie meine eigenen FHEM-Erweiterungen. 

Alle offiziellen Updates laufen doch ohnehin über SVN. Welchen Unterschied bzw. Vorteil ein Umzug hätte kann ich aktuell nicht erkennen, für mich funktioniert die aktuelle Lösung prima.

Merkwürdig finde ich dagegen, dass ich im Januar keine Benachrichtigung über deine Anfrage bekommen habe und heute nur zufällig darauf aufmerksam geworden bin.

Grüße,
Jens
